name: Issue Tracking

on:
  issues:
    types:
      - opened

jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: List command
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"

