name: Test

on:
  pull_request:
    types:
      - closed

jobs:
  task-done:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set the task as Done
      env:
        TITLE: ${{ github.event.pull_request.title }}
      run: |
        echo $TITLE
