name: Task Done

on:
  pull_request:
    types:
      - closed

jobs:
  task-done:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Set the task as Done
        env:
          API_KEY: ${{ secrets.NOTION_API_KEY }}
          DB_ID: ${{ secrets.NOTION_TASK_DB_ID }}
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          python scripts/pr_task_helper.py -secret $API_KEY -database_id $DB_ID -pr_title $TITLE
