name: Test

on:
  pull_request:
    types:
      - opened

jobs:
  task-done:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Set the task as Done
        env:
          API_KEY: ${{ secrets.NOTION_API_KEY }}
          DB_ID: ${{ secrets.NOTION_TASK_DB_ID }}
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo test
          echo $API_KEY
          echo test2
          echo $DB_ID
          echo test3
          echo $TITLE
